### ISSUE TITLE
Correspondence between material fonts and HTML elements

### ISSUE THREAD

**Issue by mercmobily** [PolymerElements/paper-styles#104]
I am trying to figure out how to use `paper-styles`. The documentation [says](https://github.com/PolymerElements/paper-styles):

> The <paper-styles> component provides simple ways to use Material Design CSS styles in your application. The following imports are available:

> ...

> * [typography.html](https://github.com/PolymerElements/paper-styles/blob/master/typography.html): Material Design [font](http://www.google.com/design/spec/style/typography.html#typography-styles) styles and sizes

`typography.html` defines several mixins, for example:

*    `--paper-font-display4: {`
*    `--paper-font-display3: {`
*    `--paper-font-display2: {`
*    `--paper-font-display1: {`
*    `--paper-font-headline: {`
*    `--paper-font-title: {`
*    `--paper-font-subhead: {`
*    `--paper-font-body2: {`
*    `--paper-font-body1: {`

My question is: which HTML element should I use with these? For example, is `font-display4` seems to be the equivalent of `h1`, but I am a big confused: is there a some kind of correspondence? Or, shall I just always use `<p>`? Is there a recommended pattern here?

**Comment by notwaldorf** [comment]
The values are based on the Material Design spec (https://www.google.com/design/spec/style/typography.html#typography-styles) and you can see them in action in the demo (https://elements.polymer-project.org/elements/paper-styles?view=demo:demo/index.html&active=paper-styles).

 They're there for you to use however you want. If you want something to look title-y, you might want to use `--paper-font-title`. But maybe you want it to be a giant, hero type title, in which case you would use one of the larger `-display` ones.

The spec goes into a whole bunch of examples of when you would use each style. Basically, they're just convenience styles, to help you style your application, but what that actually looks like is up to you.

**Comment by mercmobily** [comment]
Hi,

I realise that. My main question is: what HTML element should I use for my text?
In the demo you gave, the code is:

        <div class="paper-font-display4">Display 4</div>
        <div class="paper-font-display3">Display 3</div>
        <div class="paper-font-display2">Display 2</div>
        <div class="paper-font-display1">Display 1</div>
        <div class="paper-font-headline">Headline</div>
        <div class="paper-font-title">Title</div>
        <div class="paper-font-subhead">Subhead</div>
        <div class="paper-font-body2">Body 2</div>
        <div class="paper-font-body1">Body 1</div>
        <div class="paper-font-caption">Caption</div>
        <div class="paper-font-menu">Menu</div>
        <div class="paper-font-button">Button</div>

So it only ever uses DIVs. However, in HTML, *if* you are worried about SEO and/or HTML structure being formally correct, you would have (maybe) `<H1>` for `display4` (so it would be `<div class="paper-font-display4">Display 4</div>`), `H2` for `display3`, `H3` for `display2`, `H4` for `display1`, etc. Just wondering if there was a default, or a recommended/best practice correspondence.

From your answer, I assume not.

Thank you!

Merc.

**Comment by notwaldorf** [comment]
Oh, you can still use `<h1>`s, you just have to style them: http://jsbin.com/xidaca/edit?html,output. They're not automagically styled for you, if that's what you mean.
