### ISSUE TITLE
Update to iron-flex-layout 1.3

### ISSUE THREAD

**Issue by nomego** [PolymerElements/paper-styles#105]
Since Polymer and iron-flex-layout 1.3.0, `iron-flex-layout/classes/iron-flex-layout.html` is deprecated and causes warnings when included.

Right now, paper-styles seems to be the only paper/iron element including this the old way.

Please update to the new way, as described by https://github.com/PolymerElements/iron-flex-layout/blob/master/README.md

Thanks!

**Comment by Qvatra** [comment]
+1

**Comment by rubenstolk** [comment]
+1

**Comment by notwaldorf** [comment]
This is a pretty giant breaking change, and can't be shipped as is. Users of `paper-styles` will have to change how they use it (by doing a `style include=`, since just including the HTML isn't enough anymore

**Comment by nomego** [comment]
Well to get rid of the warning I think you only need to drop the import, skimming the source.
The only real issue with paper-styles as far as I could see is the classes/shadow-layout.html (is it even needed?)

**Comment by notwaldorf** [comment]
The problem with deleting any files is that people are using them, which counts as a breaking change. A surprising amount of people use that file directly: https://github.com/search?q=paper-styles%2Fclasses%2Fshadow-layout.html&type=Code&utf8=%E2%9C%93

**Comment by abdonrd** [comment]
Maybe we can add a warning in that file and remove in the future.

Like: https://github.com/PolymerElements/iron-flex-layout/blob/master/classes/iron-shadow-flex-layout.html#L12

**Comment by notwaldorf** [comment]
@abdonrd `paper-styles` already generates that warning because it includes `/classes/iron-flex-layout.html`, which prints a similar warning.

**Comment by abdonrd** [comment]
@notwaldorf ops, you're right! Then it's okey for me. :)

**Comment by nomego** [comment]
Actually that's the whole point of this issue.
Stop including `/classes/iron-flex-layout.html` automatically when including `paper-styles`. :)
If it's needed by `classes/shadow-layout.html`, import it there.

Glancing the code I don't see a need for it anywhere else...? (If even there..)

**Comment by notwaldorf** [comment]
Unfortunately that is still a breaking change, because it's going to break current usage, and can't be shipped until a major release 😞

**Comment by jay8t6** [comment]
any updates on this?

**Comment by mbana** [comment]
? Any updates?

**Comment by notwaldorf** [comment]
There will not be any major releases to the elements until at least October, unfortunately, so nothing we can do about this yet

**Comment by lp177** [comment]
I have finaly found this guilty ! Inserted in all my poly projects, herited by the starter kit v1 and not realy used... What is this big breaking change who then not be simply replace by a shared stylesheet ?

**Comment by notwaldorf** [comment]
This will finally be fixed in the 2.0-preview merge
