### ISSUE TITLE
--paper-font-common-nowrap escapes parent container.

### ISSUE THREAD

**Issue by ryantheleach** [PolymerElements/paper-styles#107]
I'm trying to achieve a multiline (or even single line) ellipsis on a card, but using --paper-font-common-nowrap results in the text escaping the container.

![image](https://cloud.githubusercontent.com/assets/141554/13728807/aed9912e-e973-11e5-8fc7-5dd9f29e387b.png)

```
              <style is="custom-style">
                paper-card.plugin {
                   @apply(--layout-horizontal);
                   margin-bottom: 4px;
                 }
                .plugin-image {
                  position: absolute;
                  width: 200px;
                  height: 100%;
                }
                .plugin-content {
                  margin-left: 200px;
                  @apply(--layout-flex);
                }
                .plugin-name {
                   @apply(--paper-font-title);
                 }
                .plugin-sub {
                  @apply(--paper-font-subhead);
                  color: var(--paper-grey-600);
                  margin: 4px 0;
                }
                .plugin-description {
                  @apply(--paper-font-common-nowrap);
                }
              </style>
              <paper-card class="plugin">
                <div class="plugin-image" style="background: url('./images/creeper.png'); background-size: cover;"></div>
                <div class="plugin-content">
                  <div class="card-content">
                    <div class="plugin-name">CreeperMend</div>
                    <div class="plugin-sub">Version 3.0 for API 4.1</div>
                    <div class="plugin-description">Repairs creeper explosions naturally over time! Does some other stuff as well, but I forget what, really just need this div to be a bit longer to check out how it behaves when you have really long run on sentences. Repairs creeper explosions naturally over time! Does some other stuff as well, but I forget what, really just need this div to be a bit longer to check out how it behaves when you have really long run on sentences. Repairs creeper explosions naturally over time! Does some other stuff as well, but I forget what, really just need this div to be a bit longer to check out how it behaves when you have really long run on sentences. </div>
                  </div>
                  <div class="card-actions">
                    <paper-icon-button class="plugin-icon" icon="star"></paper-icon-button>12
                    <paper-icon-button class="plugin-icon" icon="file-download"></paper-icon-button>20k
                    <paper-icon-button class="plugin-icon" icon="update"></paper-icon-button>1 Week Ago
                  </div>
                </div>
              </paper-card>
```

**Comment by IntranetFactory** [comment]
I think multi line ellipsis can't work in all browsers as even CSS3 doesn't provide an option for multi line ellipsis. A webkit only approach might be `-webkit-line-clamp`, but even that doesn't provide the expected results reliably.

I had the same problem with single line ellipsis in https://github.com/PolymerElements/paper-styles/issues/106. I still think that `--paper-font-common-nowrap` should have at least `display: inline-block` in general. In your case you need to therefore add  `display: inline-block` to your `.plugin-description`

**Comment by ryantheleach** [comment]
Cheers for the tip, but in my case it doesn't seem to work. 

I kind of feel embarrassed that I didn't check the closed issues close enough before making a duplicate.

I wonder if there is some Javascript solution that could be used to create an element that you could wrap text in.

**Comment by motss** [comment]
Set explicity width?

**Comment by ryantheleach** [comment]
Which works, but the cards are no longer responsive, and the text spills out as soon as the card is smaller then the text... there's probably something fundamental about css that I'm missing.

**Comment by ryantheleach** [comment]
I ended up using fades as I couldn't get ellipsis working nicely at all.

I still think that line clamping or working ellipsis is something that would be useful to have in paper-styles (or maybe another element)

**Comment by motss** [comment]
@ryantheleach PTAL if this is your expected result.

[Simple demo](https://jsbin.com/mixorucaku/1/edit?html,output)

**Comment by ryantheleach** [comment]
That's the result I was expecting, are you using a different library version, or is there some other styles in my page that are clashing?

**Comment by notwaldorf** [comment]
Closing, since there seems to be an answer to how to fix the original issue
