### ISSUE TITLE
<header> is not really meant to replace <h1>

### ISSUE THREAD

**Issue by tommie** [PolymerElements/paper-styles#108]
This is a really minor thing, but the example in classes/typography.html uses `<header>` in a way that makes it look like it replaces `<h1>`, which is not really the intent. [HTML5](https://www.w3.org/TR/html5/sections.html#the-header-element) has a note that hints of this:

>A header element is intended to usually contain the section's heading (an h1–h6 element), but this is not required. The header element can also be used to wrap a section's table of contents, a search form, or any relevant logos.

**Comment by notwaldorf** [comment]
Would you mind sending a PR with an update to that? It would be much appreciated! 🍦
