### ISSUE TITLE
Roboto breaks in cyrillic

### ISSUE THREAD

**Issue by AlexNasonov** [PolymerElements/paper-styles#114]
Roboto works fine only if I add '&subset=latin,cyrillic' to roboto.html...
This is weird, because it worked fine with default params a few days ago((

**Comment by notwaldorf** [comment]
I think that's a problem with the font itself, not our usage of it (we're just importing it), so I'm not sure what we can do about it. I would look at the open issues in https://github.com/google/roboto/issues, and maybe filing one there
