### ISSUE TITLE
how to set the font-size and width for the paper-input in an editable paper-slide?

### ISSUE THREAD

**Issue by Fausto-theXS** [PolymerElements/paper-styles#122]
I am trying as follow with no results so far

```
paper-slider {
  --paper-slider-input:{ 
    width:75px; font-size:small;
  }
}
```

What am I missing?
Thanks

**Comment by notwaldorf** [comment]
Argh, it seems that because `paper-slider` overrides the `--paper-input-container-input` mixin, you can set the width but not the font size: http://jsbin.com/muzace/edit?html,output

Moving this to `paper-slider`, as the issue does not belong here

**Comment by notwaldorf** [comment]
This issue was moved to PolymerElements/paper-slider#185
