### ISSUE TITLE
element-styles/paper-material.html needs a unique dom-module id

### ISSUE THREAD

**Issue by mbinette** [PolymerElements/paper-styles#130]
In 2.0-preview the standard `<paper-material>` will not be visible if you include a `<paper-button>` or `<paper-card>` in your component. 

The reason is that element-styles/paper-material.html has a component in it with the definition `<dom-module id="paper-material">` which is the exact definition that is in paper-material/paper-material.html.

The change to element-styles was added in the 1.2 tag and is used in the 2.0-preview branch and 2.0-preview branch versions of paper-card and paper-button (and maybe others?)

To repeat the issue, create a new polymer-2-starter-kit application. Modify bower.json to include paper-material and paper-button. Open my-view.html and add a `<paper-material>` with some text in it. Run the app and you will properly see the paper-material on my-view1. 

Edit my-view1.html and import paper-button. Add a paper-button under the paper-material. Run the app and you will see the button but no longer see the paper-material or its content.

The exact same issue exists for element-styles/paper-item.html

**Comment by mbinette** [comment]
Same exact issue with element-styles/paper-item.html

**Comment by notwaldorf** [comment]
Neither of those elements uses `paper-material` anymore, and in 2.0 `paper-material` is deprecated in favour of the styles, so I think this shoooould be ok. I agree that if you use both it won't work, but we recommend not using a `paper-material` element at all (since it's an anti-pattern).

Does this sound ok?

**Comment by mbinette** [comment]
OK, I removed the `<paper-material>` elements and replaced with paper-material style. Works. I didn't know the paper-material component was being deprecated in 2.0.

**Comment by notwaldorf** [comment]
Actually, I'm going to re-open this because it needs to be fixed. The `element-styles/paper-material.html` needs to be renamed to something like `paper-material-styles`, so that the `id`s don't conflict

**Comment by pimenteljchristopher** [comment]
You changed the naming for core components of paper-button .. 
![polymerv2](https://user-images.githubusercontent.com/7525071/29412994-80fcb744-838d-11e7-964c-95109b983b69.PNG)

**Comment by dman777** [comment]
@notwaldorf If I may ask, please, what is about `paper-material` is a anti-pattern? For learning and best practices.

**Comment by dman777** [comment]
@notwaldorf Just to confirm, would this be also considered a anti pattern? It seems this is just webcomponent that is styled with no JS. Where the same thing can be done without a webcomponent using `iron-overlay-backdrop`?

https://github.com/PolymerElements/iron-overlay-behavior/blob/master/demo/simple-overlay.js
