### ISSUE TITLE
switch to font-roboto-local

### ISSUE THREAD

**Issue by cordovapolymer** [PolymerElements/paper-styles#131]
Please switch to font-roboto-local because polymer-build doesn't bundle it Polymer/polymer-build#155
There's also a [pull request](https://github.com/PolymerElements/paper-styles/pull/128) which offers complete roboto removal, but I think switching to local version is safer.

**Comment by stramel** [comment]
You can stopgap this by doing `"font-roboto": "PolymerElements/font-roboto-local#^1.0.0"` in your `bower.json`

**Comment by cordovapolymer** [comment]
@stramel , thanks, that's a good solution([I have already seen it here](https://github.com/Polymer/polymer-bundler/issues/453).
