### ISSUE TITLE
Please support: --shadow-none

### ISSUE THREAD

**Issue by hawkett** [PolymerElements/paper-styles#14]
Example usage:

paper-button {
      mixin(--shadow-elevation-2dp);
}

paper-button:hover, paper-button[selected] {
      mixin(--shadow-none);
}

Thanks!

**Comment by notwaldorf** [comment]
What should `shadow-none` do? Should it turn off all the shadows?

**Comment by hawkett** [comment]
@notwaldorf - yes :)

**Comment by morethanreal** [comment]
Fixed in #40.
