### ISSUE TITLE
Styles do not get applied in Edge 40+ (creators update and above)

### ISSUE THREAD

**Issue by aarondrabeck** [PolymerElements/paper-styles#145]
### Description

None of the styles get applied to html/:root in Edge 40 and above.

### Expected outcome

Styles to work as they do in other browsers.

### Actual outcome

No styles or layouts get applies.

### Live Demo
https://www.webcomponents.org/element/PolymerElements/paper-styles/demo/demo/index.html

### Steps to reproduce

Open the demo pages for this component in Edge.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [X] Edge
- [ ] IE 11
- [ ] IE 10

![image](https://user-images.githubusercontent.com/9825025/27809782-080bb236-6010-11e7-970a-94c3ca6318ea.png)

**Comment by feuerste** [comment]
The attached screenshots actually show the problem appearing in https://www.webcomponents.org/element/PolymerElements/paper-styles/demo/demo/index.html better:
Chrome:
![screenshot_chrome](https://user-images.githubusercontent.com/362372/28970656-9e57f0f6-7929-11e7-89e5-1b0554f72f93.png)
Edge:
![screenshot_edge](https://user-images.githubusercontent.com/362372/28970657-9e5d7a6c-7929-11e7-8873-f9dceedac964.png)
