### ISSUE TITLE
Suggestion: A "Content" Class

### ISSUE THREAD

**Issue by mbleigh** [PolymerElements/paper-styles#17]
It would be great for `paper-styles` to have some kind of class or mixin or what-have-you that would let you apply material design styling to an entire block of standard HTML content. Use case would be rendering things like Markdown in a content block with nice MD styling.

Just a thought.

**Comment by morethanreal** [comment]
What kind of styling are you thinking about? Like make the content a card like-thing with a shadow, the proper fonts etc.?

**Comment by notwaldorf** [comment]
apply label: pending response. 

@mbleigh: can you take a look at @morethanreal's question, please? :)

**Comment by notwaldorf** [comment]
Closing this, since it's super ancient, and we never figured out what the original intent was :)
