### ISSUE TITLE
Request to fonts.googleapis.com for fonts is an issue

### ISSUE THREAD

**Issue by yo3jones** [PolymerElements/paper-styles#22]
There should be a configuration to not make a request to get external fonts.

There can be situations where a client does not have access to the web (just a local intranet), where this request will fail.

**Comment by Deseteral** [comment]
This is also a major problem when using Polymer with app runtimes such as nw.js or Electron.

Not only desktop apps should be able to work completely offline, but even with internet connection requesting them will fail. The files are loaded from local file system and not from the server so requesting `file://fonts.googleapis.com/css?family=Roboto...` will result with 404.

There should be a way to prevent `paper-styles` from loading Roboto from Google Fonts, and instead load it from local TTF files.

**Comment by hawkett** [comment]
+1 here for a slightly different reason - I have an app using a font other than roboto, and load it via typekit. I definitely want to continue using all the paper-styles goodness - just with an alternate font. From my perspective it would be good to take roboto out entirely in this situation - i.e. not attempt top load it either via the web or via the local filesystem. That said, making the font a local resource in the paper-styles component would be worthwhile.

**Comment by malcolmalex** [comment]
+1 for this. I am upgrading an Electron (atom-shell) app from polymer 0.5 right now, and running into this very issue (https://github.com/malcolmalex/onsight-timer).

Does anyone know how to workaround this? Is there an adjustment I can make to paper-styles in the short term?

**Comment by jklein24** [comment]
Chris, do you have any thoughts on this? It would be nice to eliminate this console error for offline and non-http{s} environments.

**Comment by jklein24** [comment]
I think bringing the font-roboto element back into PolymerElements and stubbing the import out for offline and csp use-cases would solve the problem.

**Comment by bobslaede** [comment]
+1 breaks hydolysis with the font url

**Comment by coreyfarrell** [comment]
+1 I think it's very important for all iron and paper elements to use relative paths only, nothing from external servers.  Maybe it's best for paper-styles to just not import the font?  Leave this to the application to do it or not.  Otherwise the font should definitely be imported from font-roboto (or maybe it should be called iron-font-roboto?).  This way an application build can use a minimal replacement repo to exclude that font.

**Comment by Quelu** [comment]
+1 for the use in Electron or nw.js apps

**Comment by AlmirKadric** [comment]
+1

**Comment by RNCRyan** [comment]
+1; We're using Polymer in a Cordova cross-platform app, and the remote resource path for fonts is a big problem for us.

**Comment by butterandfly** [comment]
+1，it will be great to the Chinese people, who are under the DOG SHIT GREAT FIRE WALL

**Comment by azakus** [comment]
FWIW, Google's Font CDN will do a *much* better job at serving the exactly browser what your app needs, by doing a lot of server side font magic.

That said, the font files are here: https://github.com/google/roboto/tree/master/out/RobotoTTF

It would only take a small bit of CSS font definition work to package that up.

**Comment by RNCRyan** [comment]
I totally agree that Google Font CDN is best when accessing from the web... but it doesn't work when you have a packaged app (since the requests go out under the parent protocol, which is file://).

**Comment by Deseteral** [comment]
You could use [electron-compile](https://github.com/paulcbetts/electron-compile) to fix this.
I haven't tried it yet but according to [this](https://twitter.com/paulcbetts/status/613049354350383104) it should work.

**Comment by azakus** [comment]
As an aside, I made https://github.com/PolymerElements/font-roboto-local that uses a local set of TTF files for Roboto for environments where no external code can load.

The Font CDN will be still be better in the majority case.

**Comment by azakus** [comment]
Fixed by #44

**Comment by rubenstolk** [comment]
For others who need something solid which works in offline cases:

```json
{
  "dependencies": {
    "font-roboto": "git@github.com:safetychanger/font-roboto#1.0.1"
  },
  "resolutions": {
    "font-roboto": "git@github.com:safetychanger/font-roboto#1.0.1"
  }
}
```

**Comment by sbley** [comment]
If I wanted to use <roboto-font-local> instead of <roboto-font> what would be the best way to make <paper-styles> include the local fonts in favor of CDN?

**Comment by rubenstolk** [comment]
See my comment above, that does the trick.

**Comment by sbley** [comment]
Your solution doesn't work for me. It still downloads font-roboto from Polymer. Obviously, it gives precendence to the dependency definition in paper-styles' bower.json. Does it require a minimum bower version? I am on 1.5.3.

**Comment by sbley** [comment]
Okay, apparently the font-roboto dependency has to be put *after* the Polymer dependencies. Last one wins. :cool:

**Comment by s-trooper** [comment]
what is here a solution? i don't like to have "fonts.googleapis.com" request nor "fonts.googleapis.com".

**Comment by gar1t** [comment]
Any update here? I'll chime in with others that the hard-wired dependency on Google's CDN is a problem that should be addressed. Others have enumerated the specific reasons, which I think sufficiently make the case.

I don't know enough about the correct patterns in Polymer to suggest an approach, much less provide a PR. But some thoughts:

- Default fonts should not be external - "sans serif" should be perfectly fine as a starting point

- The application should be responsible for specifying alternative fonts (external are fine in this case)

If for some odd reason Roboto must by decree by the default font (I can't imagine why branding is so important here, but for argument sake) then provide a way to control the font location, short of patching upstream sources.

Certainly the framework developers don't want to be open to privacy concerns in having Google hard-wire a call back to their servers simply for the sake of a default font :)
