### ISSUE TITLE
Styles cannot be used in custom elements with real Shadow-dom via HTML import

### ISSUE THREAD

**Issue by tiesselune** [PolymerElements/paper-styles#32]
When styling custom Polymer elements, the styles provided by `paper-styles` work under the Shady DOM implementation, but not with real Shadow DOM since the styles encapsulation does not work the same way.

Then I think it is currently impossible to use the material classes in a custom Polymer element out of the box ~~without duplicating them or making them bleed out everywhere~~  if using real Shadow DOM, and that might cause issues when it becomes the default behaviour.

The fact that the styles don't bleed out in local DOMs seems a rather good practice however.

As a suggestion, it would be nice to have the styles encapsulated in a .css stylesheet to be included into custom Polymer elements so that those styles are available *on-demand* even with real Shadow DOM.

**Comment by morethanreal** [comment]
We recommend using the custom properties defined in `paper-styles` to style local DOM. The custom properties are available without being imported into every shadow root, and you can use them to style the host element without worrying about conflict with user-defined classes.

**Comment by tiesselune** [comment]
Is it safe to use mixins and custom properties under older browsers falling back to shady dom then? Or should we use both normal classes and mixins in order for it to be compatible with all the supported browsers?

**Comment by morethanreal** [comment]
Mixins and custom properties are shimmed by the Polymer library, and they are safe to use in shady DOM. The classes are really provided for legacy reasons, and for when using custom properties are inconvenient (for example, in the main document).

**Comment by tiesselune** [comment]
Everything is fine then. Thanks for the explanation!
