### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by liebrand** [PolymerElements/paper-styles#34]
It would be great if these variables could have some documentation on them as to where and how they are used.

In particular things like difference between "text-primary-color" vs "primary-text-color" would be good to understand.

**Comment by karan** [comment]
+1 

@nevir

**Comment by Sinjins** [comment]
+1

**Comment by jscissr** [comment]
+1

**Comment by BlackGlory** [comment]
+1

**Comment by abdonrd** [comment]
+1

**Comment by gjuchault** [comment]
+1

**Comment by dsschnau** [comment]
+1

It looks like the classes are written to spec for material design (as they should be), for example the typography demo lines up perfectly with [the material design typography spec](http://www.google.com/design/spec/style/typography.html#typography-styles), so until the docs are better that's a good reference point

**Comment by notwaldorf** [comment]
Assigning to @arthurevans. I've created a PR that adds a small docs blurb (https://github.com/PolymerElements/paper-styles/pull/59), but let me know if you want to do a tutorial page on this. If not, feel free to close it :)

**Comment by notwaldorf** [comment]
I fixed this!

**Comment by arthurevans** [comment]
Thank you! :cake: :camel: :100:
