### ISSUE TITLE
Relative protocol in font URL breaks in Chrome extension

### ISSUE THREAD

**Issue by OliverJAsh** [PolymerElements/paper-styles#39]
https://github.com/PolymerElements/paper-styles/blob/d23af125cb74978532c25e5cd152f9b2e6d991c8/typography.html#L11

This will resolve to `chrome://`, which obviously will never work.

Can we be explicit about the protocol?

**Comment by addyosmani** [comment]
:+1:

**Comment by azakus** [comment]
Fixed by #44
