### ISSUE TITLE
Demos and Docs not plugged into Polymer 1.0 Element Catalog

### ISSUE THREAD

**Issue by Sinjins** [PolymerElements/paper-styles#48]
Noticed that paper-styles demo and docs are not yet plugged into Polymer 1.0's Element Catalog:  https://elements.polymer-project.org/elements/paper-styles

**Comment by kanitw** [comment]
+1

**Comment by erichnascimento** [comment]
+1

**Comment by abdonrd** [comment]
+1

**Comment by voondo** [comment]
+1

**Comment by dsschnau** [comment]
+1

**Comment by smbatpetrosyan** [comment]
+1

**Comment by garlicnation** [comment]
This can be fixed by adding an HTML comment ending with `@pseudoElement paper-styles`.

**Comment by samccone** [comment]
cool TIL pseudo element
