### ISSUE TITLE
/deep/ combinator is deprecated

### ISSUE THREAD

**Issue by jscissr** [PolymerElements/paper-styles#49]
[classes/shadow-layout.html](https://github.com/PolymerElements/paper-styles/blob/master/classes/shadow-layout.html) uses `/deep/` which triggers a warning in Chrome:

> /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

**Comment by MetaMemoryT** [comment]
:+1: This is still a problem.

**Comment by notwaldorf** [comment]
This will finally be fixed in the 2.0-preview merge
