### ISSUE TITLE
Compatibility with Polymer 1.1

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-styles#53]
With [the release of Polymer 1.1](https://blog.polymer-project.org/announcements/2015/08/13/1.1-release/), there are new style recommendations and features.

**Comment by notwaldorf** [comment]
@abdonrd What are the changes that are needed? I don't think any of these (other than `demo.css` which I want to nuke from space) import css files, so the shared style modules won't help much?

**Comment by abdonrd** [comment]
This PR is very old, the `paper-styles` has had many changes. I think now `paper-styles` are :ok_hand:.

**Comment by notwaldorf** [comment]
Yayyyy! Sorry for the slow triaging. We're working on fixing it this year and actually getting to things on time! :)

**Comment by abdonrd** [comment]
Sounds great! :)
