### ISSUE TITLE
Paper-styles loads fonts online.

### ISSUE THREAD

**Issue by vshab** [PolymerElements/paper-styles#56]
Paper-styles depends on font-roboto causing application to load fonts from google service. This leads to problems with offline applications.

Can you use font-roboto-local instead?

**Comment by sbley** [comment]
+1

**Comment by makrolabs** [comment]
+1

**Comment by ebidel** [comment]
If you want to use local fonts, you can use https://github.com/PolymerElements/font-roboto-local. Make sure to update your bower.json so any import that references `font-roboto/roboto.html` will use the local version:

    "font-roboto": "PolymerElements/font-roboto-local"

**Comment by makrolabs** [comment]
Thanks!

**Comment by notwaldorf** [comment]
Closing, as @ebidel's answer is the :trophy:

**Comment by mikaelharsjo** [comment]
So say I want to use `paper-styles` with `font-roboto-local`. How would my `bower.json` look?

```
  "dependencies": {
    "paper-styles": "polymerelements/paper-styles#~1.0.3"
  },
  "overrides": {
      "paper-styles": {
        "dependencies": {
          "font-roboto": "polymerelements/font-roboto-local"
        }
      }
  }
```
I tried this but no joy.

**Comment by ebidel** [comment]
It should just be:

```
"dependencies": {
    "paper-styles": "polymerelements/paper-styles#~1.0.3",
    "font-roboto": "polymerelements/font-roboto-local"
  },
```

That will install the local version into `font-roboto`. It should just work :)

**Comment by mikaelharsjo** [comment]
That's magical!
