### ISSUE TITLE
How to override default-theme.html?

### ISSUE THREAD

**Issue by vysinsky** [PolymerElements/paper-styles#61]
Hi,
I've created theme.html which I import as last and sometimes it works. But if - from some reason - default-theme.html is loaded after my custom theme file it overrides all variables (I am overriding --default-primary-color for example). How to properly override default theme? Thanks

I've found, that paper-styles.html (which imports default-theme.html) is imported from some polymer/paper components. I do not import default-theme.html on my own.

**Comment by notwaldorf** [comment]
This is the same problem as you would for CSS files. If you have two files that define the same style, then the last imported file wins.

One thing to try out is in your "main" application file, after you've imported all your elements, to then import your `custom-theme.html`. If you want to be super extra sure, 

/cc @sorvell @cdata for better ideas.

**Comment by Zyzle** [comment]
@notwaldorf Sorry to drag up a closed issue like this but I'm having the same problem noted by @vysinsky.  No matter where I put the `app-theme.html` file in the index it always seems to be loaded before the elements in my `elements.html` file (my site has a similar structure to the polymer-starter-kit with all the paper-elements imported in a single file).

I have found if I add my `app-theme.html` import code to the end of my `elements.html` and create a `dist` version of my project by `vulcanizing` the `elements.html` it works as expected.

This only seems to be an issue in Chrome though.  When I try the same site in Firefox the `app-theme.html` does appear to be applied properly. I've tried multiple cache clearings and the problem doesn't seem to be related to anything left over in the browser.

**Comment by broken** [comment]
This was trickier than it needed to be to find, and should really be in the documentation somewhere as some hint. I couldn't figure out why my document-level custom-style :root properties were not being applied. After rereading the documentation carefully multiple times, I finally noticed that default-theme.html was being loaded by a paper element.

I'm not sure if the expectation is to modify this file (which seems like bad practice), but some sort of heads up in the Polymer styling guide would be nice. For our AppEngine app, our current solution is to set a skip_files rule for this file so the browser will just 404 when it is requested.

**Comment by ShaggyDude** [comment]
I am building a cms where the user picks the colors. I need to be able to pipe these colors to the whole app. Not sure exactly how to achieve this at this point.
