### ISSUE TITLE
Opacity for dark text mismatches with Material Design specification

### ISSUE THREAD

**Issue by ronnyroeller** [PolymerElements/paper-styles#67]
The Material Design specifications says that icons with dark text should use an opacity of 38% (https://www.google.com/design/spec/style/color.html#color-ui-color-application).

Paper-styles indicates that icons should use the secondary opacity (54%) (https://github.com/PolymerElements/paper-styles/blob/master/color.html#L322)

Additionally, the spec says that the hint/disabled opacity should be 38% whereas paper-styles implements 26%.

**Comment by ronnyroeller** [comment]
I created a Pull Request to solve this issue: https://github.com/PolymerElements/paper-styles/pull/69

**Comment by Pupix** [comment]
A follow up question. These [[1]](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3Z21kckdVNjFiN2c/style_color_uiapplication_alpha1.png) [[2]](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3dnF5cTktSjdTajA/style_color_uiapplication_alpha2.png) pictures show different values than the following tables for icons.

| Dark text (#000000) | Opacity |
| ------------- |:-------------:| -----:|
|Primary text | 87%|
|Secondary text | 54%|
|Hint text, disabled text and icons | 38% |

| Light text (#FFFFFF) | Opacity |
| ------------- |:-------------:| -----:|
| Primary text | 100% |
| Secondary text | 70% |
| Hint text, disabled text and icons | 30% |

Also there's a line saying 

> Hint and disabled text and **icons have an opacity of 38% for dark content on light backgrounds, and an opacity of 30% for white content on dark backgrounds**.

and 2 paragraphs later it says

> Elements like **icons** and dividers **benefit from having a hex value of black or white** so that they work on backgrounds of any color.


@notwaldorf Do you happen to know which of these guidelines is right?

Do I have to use icons with opacity like the `secondary text`, with opacity like the `hint/disabled text` or directly a `hex color with no opacity`?
