### ISSUE TITLE
primary-text-color vs text-primary-color

### ISSUE THREAD

**Issue by MajorBreakfast** [PolymerElements/paper-styles#81]
Why is there a `primary-text-color` and a `text-primary-color`?

**Comment by abdonrd** [comment]
I ask the same here: https://github.com/PolymerElements/polymer-starter-kit/issues/436. :)

**Comment by notwaldorf** [comment]
I honestly don't know the origin of this, and unfortunately we're now in a situation where both are probably in use, so none can be deleted without being seen as a giant breaking change. :(

`primary-text-color` looks like the right one (87% of #000), and `text-primary-color` is white and I don't know what it's intentions are. I will add a comment to try to discourage people from using it. 

I know this isn't a very satisfying answer, but it's what I got!

**Comment by MajorBreakfast** [comment]
Excellent
