### ISSUE TITLE
dependencies not listed in main in bower.json

### ISSUE THREAD

**Issue by HaykoKoryun** [PolymerElements/paper-styles#84]
When running `bower-installer` on my project with a dependency on `paper-styles` I noticed an issue where a bunch of files were missing once the `main` files had been copied over to my chosen folder. The issue is because dependencies for this component have not been listed in `main`.

Currently the `main` property in `bower.json` is just the main component file `paper-styles.html` like so:
```javascript
"main": "paper-styles.html"
```

however in order for it to work correctly it should be:
```javascript
"main": [
	"paper-styles.html",
	"color.html",
	"default-theme.html",
	"shadow.html",
	"typography.html"
],
```

(As an example, the [`neon-animation`](https://github.com/PolymerElements/neon-animation) component has the dependencies [listed](https://github.com/PolymerElements/neon-animation/blob/aa236931aab2fd3b15948e0305cf6c71b627ef24/bower.json#L14-L23) correctly)

**Comment by David-Mulder** [comment]
You might be misunderstanding the concept of `main` in `bower.json`. `main` lists the (main) entry points in to a module. They do not list all necessary files for a module to work and references from inside the entry points still need to be followed (e.g. in this case `paper-styles.html` references he other 4 files). In other words it's not downright incorrect to list the other 4 files explicitly (as they can be used on their own), however you shouldn't be copying the `main` files blindly without following their references as well.

**Comment by HaykoKoryun** [comment]
@David-Mulder yeah, I've been reading more about the `main` property after your comment and it seems that `bower` decided that's the purpose of the `main` early this year without adding a proposed `files` field as a replacement for the way people were using `main` before.

There is the `vulcanize` tool, but in a pure `php` project (at least when it comes to the server side) I would need to write my own tool to follow html imports after all bower packages have been installed to cherry pick what needs to go into production.

For a different project, I ended up writing a small "fixer" script in `Node.js` that runs after `bower install` but before `bower-installer` to manually add the files I know each component needs to `main` , so that `bower-installer` will move all of the required files to the `production` folder (until there's a better solution).

**Comment by David-Mulder** [comment]
@HaykoKoryun As long as you don't mix HTML with PHP it should be easy enough to use `vulcanize` just fine. Just put your imports in an `elements.html` file and vulcanize the `elements.html` file whilst ignoring the rest. (Of course not as neat as vulcanizing the entire page, but still totally adequate).

**Comment by thijstriemstra** [comment]
There are no HTML files present, even when installing from git. Using bower 1.7.1.
```
$ bower install https://github.com/PolymerElements/paper-styles.git
bower paper-styles#*        not-cached https://github.com/PolymerElements/paper-styles.git#*
bower paper-styles#*           resolve https://github.com/PolymerElements/paper-styles.git#*
bower paper-styles#*          checkout v1.1.1
bower paper-styles#*          resolved https://github.com/PolymerElements/paper-styles.git#1.1.1
bower paper-styles#^1.0.4       cached git://github.com/PolymerElements/paper-styles.git#1.1.1
bower paper-styles#^1.0.4     validate 1.1.1 against git://github.com/PolymerElements/paper-styles.git#^1.0.4

$ ls -l bower_components/paper-styles/
total 24
-rw-r--r--  1 thijstriemstra  staff  3303 Dec 17 20:13 CONTRIBUTING.md
-rw-r--r--  1 thijstriemstra  staff  1775 Dec 17 20:13 README.md
-rw-r--r--  1 thijstriemstra  staff   875 Dec 17 20:13 bower.json
drwxr-xr-x  3 thijstriemstra  staff   102 Dec 22 15:03 classes
```

**Comment by robdodson** [comment]
@thijstriemstra can you try running `bower cache clean`, deleting the `bower_components` directory, and then running `bower install PolymerElements/paper-styles` again? I just tried in bower 1.7.1 with a clean cache and it seemed to work

**Comment by thijstriemstra** [comment]
Thanks @robdodson, that worked!

**Comment by samccone** [comment]
:+1: boom

**Comment by robdodson** [comment]
Glad to hear it, props to @samccone for the fix :)
