### ISSUE TITLE
Typography.html is using "font-roboto" , can it use "font-roboto-local" ?

### ISSUE THREAD

**Issue by raghav135** [PolymerElements/paper-styles#87]
When we try to use the web components offline , it is not working properly since "typography.html" is using "font-roboto" which is using fonts.googleapis.com.

Is it alright if typography.html uses "font-roboto-local" instead?

**Comment by ebidel** [comment]
See http://stackoverflow.com/questions/31441720/overriding-dependencies-in-bower-json-file

**Comment by raghav135** [comment]
Thanks, it is working fine with solution provided.

Just curious as to why we should not change the dependency to font-roboto-local by default.

**Comment by ebidel** [comment]
The fonts api is highly optimized and cached. It's likely users will already have the roboto funny in the cache rather than needing to download if you were to use a local font.
