### ISSUE TITLE
Text Colors

### ISSUE THREAD

**Issue by JosefJezek** [PolymerElements/paper-styles#90]
Could you add text colors for color palettes to [color.html](https://github.com/PolymerElements/paper-styles/blob/master/color.html)?
https://www.google.com/design/spec/style/color.html#color-color-palette

Check out the PSK+ default-theme
https://github.com/StartPolymer/polymer-starter-kit-plus/blob/master/app/themes/default-theme/variables.css#L49-L51

**Comment by notwaldorf** [comment]
Hmm, I don't think they belong in `color.html`, those look like the values in `default-theme.html`. Just so I understand, are you basically asking to also add `text-dark` and `text-light`, or am I missing the point entirely? :)

**Comment by JosefJezek** [comment]
Each color in Material Color Palette have defined own text color.
I would like get text colors from variables. Like this

In color.html of paper-styles
```
--paper-text-pink-a200: #fff;                                
--paper-text-pink-a100: rgba(0, 0, 0, .87);
--paper-text-pink-a400: rgba(255, 255, 255, .87);
```

In PSK+
```
--text-accent-color:               var(--paper-text-pink-a200);
--text-light-accent-color:         var(--paper-text-pink-a100);
--text-dark-accent-color:          var(--paper-text-pink-a400);
```

**Comment by JosefJezek** [comment]
![image](https://cloud.githubusercontent.com/assets/2110319/12585674/57c8085c-c44d-11e5-8825-7d85983fdb85.png)

**Comment by notwaldorf** [comment]
`color.html` just has all of the colours in the Material Design spec (https://www.google.com/design/spec/style/color.html#color-color-palette). `--paper-text-pink-a200` is not a color defined in that spec, so it can't be added to it.

We're not using any of these values in any of the elements, so it's a bit weird to add them to `default-theme.html`, I think. They seem to be very PSK-specific, so I think they belong in application-specific theme files.

/cc @addyosmani if he disagrees
