### ISSUE TITLE
error color variable missing

### ISSUE THREAD

**Issue by IntranetFactory** [PolymerElements/paper-styles#94]
I'm missing a variable for the Material Design errror color
https://www.google.com/design/spec/patterns/errors.html#errors-user-input-errors

**Comment by notwaldorf** [comment]
Hiya,

`paper-input` just uses `--google-red-500` from `color.html`. Do you mean that we should add it as a custom property to `default-theme.html`? If so, are you interesting perhaps in sending a PR for that? :)

**Comment by IntranetFactory** [comment]
Based on https://www.google.com/design/spec/patterns/errors.html#errors-user-input-errors I think it should be `--paper-deep-orange-a700`

How should the error variable be named? Should then `paper-input` also be changed?

**Comment by notwaldorf** [comment]
Oh! I think you're right! How about naming it `--error-color` in `default-theme.html`, and giving it that value? And sure, we can then get `paper-input` to use the variable instead too. 👍

**Comment by notwaldorf** [comment]
Fixed in #95
